OmniLearn/LMS/LMS/urls.py
from django.contrib import admin
from django.urls import path,include
from assessment import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('assessment.urls',namespace="assessment"))
]

OmniLearn/LMS/assessment/urls.py
from django.urls import path
from django.conf.urls import url
from assessment import views


app_name = 'assessment'

urlpatterns = [
    path('', views.assementCreate.as_view(),name="home"),
    url(r'^result/(?P<pk>\d+)/$',views.assementUpdate.as_view(),name="result"),
    path('login/', views.user_login,name="user_login"),
    path('logout/',views.user_logout,name='logout'),
    path('myassment/',views.assementList.as_view(),name="myassmentment"),
    url(r'^ajax/userResult/$',views.assement_result,name="userResultData")
]

OmniLearn/LMS/assessment/models.py
from django.db import models
from django.urls import reverse
from django import forms
from django.contrib.auth.models import User
from django.utils import timezone
# Create your models here.

class userAssements(models.Model):
    A1 = models.PositiveIntegerField(default=0,verbose_name="1. How often do you feel you are making progress towards accomplishing your goals? (0 - never, 5 - always)")
    E1 = models.PositiveIntegerField(default=0,verbose_name="2. How often do you become absorbed in what you are doing? (0 - never, 5 - always)")
    P1 = models.PositiveIntegerField(default=0,verbose_name="3. In general, how often do you feel joyful? (0 - never, 5 - always)")
    N1 = models.PositiveIntegerField(default=0,verbose_name="4. In general, how often do you feel anxious? (0 - never, 5 - always)")
    A2 = models.PositiveIntegerField(default=0,verbose_name="5. How often do you achieve the important goals you have set for yourself? (0 - never, 5 - always)")
    H1 = models.PositiveIntegerField(default=0,verbose_name="6. In general, how would you rate your health? (0 - terrible, 5 - excellent)")
    M1 = models.PositiveIntegerField(default=0,verbose_name="7. In general, to what extent do you lead a purposeful and meaningful life? (0 - not at all, 5 - completely)")

    R1 = models.PositiveIntegerField(default=0,verbose_name="8. To what extent do you receive help and support from others when you need it? (0 - not at all, 5 - completely)")
    M2 = models.PositiveIntegerField(default=0,verbose_name="9. In general, to what extent do you feel that what you do in your life is valuable and worthwhile? (0 - not at all, 5 - completely)")
    E2 = models.PositiveIntegerField(default=0,verbose_name="10. In general, to what extent do you feel excited and interested in things? (0 - not at all, 5 - completely)")
    Lon = models.PositiveIntegerField(default=0,verbose_name="11. How lonely do you feel in your daily life? (0 - not at all, 5 - completely)")
    H2 = models.PositiveIntegerField(default=0,verbose_name="12. How satisfied are you with your current physical health? (0 - not at all, 5 - completely)")
    P2 = models.PositiveIntegerField(default=0,verbose_name="13. In general, how often do you feel positive? (0 - never, 5 - always)")
    N2 = models.PositiveIntegerField(default=0,verbose_name="14. In general, how often do you feel angry? (0 - never, 5 - always)")

    A3 = models.PositiveIntegerField(default=0,verbose_name="15. How often are you able to handle your responsibilities? (0 - never, 5 - always)")
    N3 = models.PositiveIntegerField(default=0,verbose_name="16. In general, how often do you feel sad? (0 - never, 5 - always)")
    E3 = models.PositiveIntegerField(default=0,verbose_name="17. How often do you lose track of time while doing something you enjoy? (0 - never, 5 - always)")
    H3 = models.PositiveIntegerField(default=0,verbose_name="18. Compared to others of your same age and sex, how is your health? (0 - terrible, 5 - excellent)")
    R2 = models.PositiveIntegerField(default=0,verbose_name="19. To what extent do you feel loved? (0 - not at all, 5 - completely)")
    M3 = models.PositiveIntegerField(default=0,verbose_name="20. To what extent do you generally feel you have a sense of direction in your life? (0 - not at all, 5 - completely)")
    R3 = models.PositiveIntegerField(default=0,verbose_name="21. How satisfied are you with your relationships? (0 - not at all, 5 - completely)")
    P3 = models.PositiveIntegerField(default=0,verbose_name="22. In general, to what extent do you feel contented? (0 - not at all, 5 - completely)")
    hap = models.PositiveIntegerField(default=0,verbose_name="23. Taking all things together, how happy would you say you are? (0 - not at all, 5 - completely)")

    Q1 = models.PositiveIntegerField(default=0,verbose_name="1. Tension in the body, like tense muscles, sore back or neck")
    Q2 = models.PositiveIntegerField(default=0,verbose_name="2. Difficulty falling asleep or finding yourself over sleeping?")
    Q3 = models.PositiveIntegerField(default=0,verbose_name="3. Having Mood Swings")
    Q4 = models.PositiveIntegerField(default=0,verbose_name="4. Experiencing Irritation or anger with things outside of your control")
    Q5 = models.PositiveIntegerField(default=0,verbose_name="5. Facing Health Issues like headaches, stomach upsets, rashes on the body etc")
    Q6 = models.PositiveIntegerField(default=0,verbose_name="6. Irregular Eating Habits like eating too much or too little")
    Q7 = models.PositiveIntegerField(default=0,verbose_name="7. Discomfort in communicating with people in your work place or personal life")
    Q8 = models.PositiveIntegerField(default=0,verbose_name="8. Getting tired easily or experiencing fatigue")
    Q9 = models.PositiveIntegerField(default=0,verbose_name="9. Bouts of boredeom or feeling low")
    Q10 = models.PositiveIntegerField(default=0,verbose_name="10. Feeling upset because of something that happened unexpectedly")
    Q11 = models.PositiveIntegerField(default=0,verbose_name="11. Finding it difficult to cope with all the things that you have to do")
    Q12 = models.PositiveIntegerField(default=0,verbose_name="12. Finding the need to take intoxicants or stimulants")

    going_beyond_stress = models.BooleanField(default=False,verbose_name="Going Beyond Stress")
    finding_sustained_happiness = models.BooleanField(default=False,verbose_name="Finding Sustained Happiness")
    mental_emotional_wellness = models.BooleanField(default=False,verbose_name="Mental & Emotional Wellness")
    positive_parenting = models.BooleanField(default=False,verbose_name="Positive Parenting")
    healthy_relationship = models.BooleanField(default=False,verbose_name="Healthy Relationships")
    accelerated_professional_growth = models.BooleanField(default=False,verbose_name="Accelerated Professional Growth")
    healthy_lifestyle = models.BooleanField(default=False,verbose_name="Healthy Lifestyle")
    coping_with_the_covid_situation = models.BooleanField(default=False,verbose_name="Coping with the Covid Situation")

    created_date = models.DateTimeField(auto_now=True,blank=True)

    user = models.ForeignKey(User, on_delete=models.CASCADE,verbose_name="Created By")

    def CreateDate(self):
        return str(timezone.localtime(self.created_date).strftime("%d %b, %Y, %I:%M %p %Z"))

    def CreateBy(self):
        return str(self.user)

    def get_absolute_url(self):
        return reverse('assessment:myassmentment')

OmniLearn/LMS/assessment/views.py
from django.shortcuts import render
from django.views.generic import View,TemplateView,ListView,DetailView,CreateView,UpdateView,DeleteView
from . import models
from django.urls import reverse_lazy
from django.contrib.auth import authenticate,login,logout
from django.http import HttpResponseRedirect,HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.contrib.auth.models import User
from django.http import JsonResponse
import pdb
from django.core import serializers

@method_decorator(login_required(login_url='assessment:user_login'),name='dispatch')
class assementCreate(CreateView):
    model = models.userAssements
    fields = ("A1","E1","P1","N1","A2","H1","M1","R1","M2","E2","Lon","H2","P2","N2","A3","N3","E3","H3","R2","M3","R3","P3","hap",
                "Q1","Q2","Q3","Q4","Q5","Q6","Q7","Q8","Q9","Q10","Q11","Q12","going_beyond_stress","finding_sustained_happiness",
                "mental_emotional_wellness","positive_parenting","healthy_relationship","accelerated_professional_growth",
                "healthy_lifestyle","coping_with_the_covid_situation","user")
    template_name = 'assessment/index.html'


@method_decorator(login_required(login_url='assessment:user_login'),name='dispatch')
class assementUpdate(UpdateView):
    model = models.userAssements
    fields = ("A1","E1","P1","N1","A2","H1","M1","R1","M2","E2","Lon","H2","P2","N2","A3","N3","E3","H3","R2","M3","R3","P3","hap",
                "Q1","Q2","Q3","Q4","Q5","Q6","Q7","Q8","Q9","Q10","Q11","Q12","going_beyond_stress","finding_sustained_happiness",
                "mental_emotional_wellness","positive_parenting","healthy_relationship","accelerated_professional_growth",
                "healthy_lifestyle","coping_with_the_covid_situation","user")

    template_name = 'assessment/userAssements_list.html'

class assementList(ListView):
    context_object_name = 'myAssments'
    model = models.userAssements

    def get_queryset(self):
        assessmentList = {}
        if self.request.user.is_superuser:
            assessmentList = models.userAssements.objects.all()
        else:
            assessmentList = models.userAssements.objects.filter(user=self.request.user).order_by('-created_date')
        return assessmentList


def user_login(request):
    if request.user.is_authenticated:
        return HttpResponseRedirect(reverse('assessment:home'))
    if request.method == "POST":
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username,password=password)

        if user:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse('assessment:home'))
            else:
                return HttpResponseRedirect("ACCOUNT NOT ACTIVE!")
        else:
            print("somewone tried to login and failed")
            print("UserName: {} and Password {}".format(username,password))
            return render(request,'assessment/login.html',{"invalid":"Username OR Password Invalid"})
    else:
        template_name = 'assessment/login.html'
        return render(request,template_name,{})

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('assessment:home'))

def assement_result(request):
    model = models.userAssements
    asseesmentKey = request.GET.get('pk')
    result = model.objects.get(pk=asseesmentKey)
    data = {
    'A1':result.A1,
    'E1':result.E1,
    'P1':result.P1,
    'N1':result.N1,
    'A2':result.A2,
    'H1':result.H1,
    'M1':result.M1,
    'R1':result.R1,
    'M2':result.M2,
    'E2':result.E2,
    'Lon':result.Lon,
    'H2':result.H2,
    'P2':result.P2,
    'N2':result.N2,
    'A3':result.A3,
    'N3':result.N3,
    'E3':result.E3,
    'H3':result.H3,
    'R2':result.R2,
    'M3':result.M3,
    'R3':result.R3,
    'P3':result.P3,
    'hap':result.hap,

    'Q1':result.Q1,
    'Q2':result.Q2,
    'Q3':result.Q3,
    'Q4':result.Q4,
    'Q5':result.Q5,
    'Q6':result.Q6,
    'Q7':result.Q7,
    'Q8':result.Q8,
    'Q9':result.Q9,
    'Q10':result.Q10,
    'Q11':result.Q11,
    'Q12':result.Q12,

    'CQ1':result.going_beyond_stress,
    'CQ2':result.finding_sustained_happiness,
    'CQ3':result.mental_emotional_wellness,
    'CQ4':result.positive_parenting,
    'CQ5':result.healthy_relationship,
    'CQ6':result.accelerated_professional_growth,
    'CQ7':result.healthy_lifestyle,
    'CQ8':result.coping_with_the_covid_situation
    }
    return JsonResponse(data)

OmniLearn/LMS/assessment/templates/assessment/assmentUpdate.html
{% extends "assessment/base.html" %}
{% block body_block %}
<div id="form-id" class="mt-5">
<!-- <h1 class="text-right">
<a href="{% url 'assessment:home' %}" class="text-decoration-none">&#10008;</a>
</h1> -->
<form id="resultForm" class="d-none">
  {{form.as_p}}
</form>


<div class="form-result">
  <p><b>Based on your responses, Your scores on various parameters of Wellbeing are as follows:</b></p>
  <table id="result-table" class="table table-striped table-bordered">
    <tbody>
    </tbody>
  </table>
  <p>&nbsp;</p>
  <p id="levelOfStressSentance1"></p>
  <p id="levelOfStressSentance2"></p>
  <p><b>Based on your responses & preference, you may begin your navigation journey from:</b></p>
  <div class="insprio">

  </div>
  <p><b>Disclaimer: Test results on the self-assessment scale do not reflect any particular diagnosis or course of treatment.
    They are meant as a tool to help assess your current level of Stress and Wellbeing. Should you have any further concerns about your current well-being, you may contact a certified medical physician.</b></p>
</div>

{% endblock %}

OmniLearn/LMS/assessment/templates/assessment/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.24/css/dataTables.bootstrap4.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
  <script type="text/javascript" src="https://cdn.datatables.net/1.10.24/js/jquery.dataTables.min.js"></script>
  <script type="text/javascript" src="https://cdn.datatables.net/1.10.24/js/dataTables.bootstrap4.min.js">

  </script>
  <link rel="stylesheet" href="{% static 'css/mystyle.css' %}">
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container">
        <a class="navbar-brand" href="{% url 'assessment:home' %}">Isha</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
          <div class="navbar-nav">
            <!-- <a class="nav-item nav-link active" href="{% url 'assessment:home' %}">Home <span class="sr-only">(current)</span></a> -->
            {% if user.is_authenticated %}
              <a class="nav-item nav-link active" href="{% url 'assessment:home' %}">Home</a>
              {% if user.is_superuser %}
                <a class="nav-item nav-link active" href="{% url 'admin:index' %}">Admin</a>
              {% endif %}
              <a class="nav-item nav-link active" href="{% url 'assessment:myassmentment' %}">My Assessment</a>
              <!-- <a href="{% url 'assessment:logout' %}" class="nav-item nav-link">Logout</a> -->
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  {{user.username}}
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                  <a href="{% url 'assessment:logout' %}" class="dropdown-item">Logout</a>
                </div>
              </li>
            {% else %}
              <a href="{% url 'assessment:user_login' %}" class="nav-item nav-link" >Login</a>
            {% endif %}
          </div>
        </div>
      </div>
    </nav>
    <div class="container">
      {% block body_block %}
      {% endblock %}
    </div>
    <script type="text/javascript" src="{% static 'js/myscript.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/formvalidation.js' %}"></script>
  </body>
</html>

OmniLearn/LMS/assessment/templates/assessment/login.html
{% extends "assessment/base.html" %}
{% block body_block %}
<div class="card mt-5">
  <div class="card-body">
    <h1>Please Login</h1>
    {% if invalid %}
    <div class="alert alert-danger" role="alert">
      {{invalid}}
    </div>
    {% endif %}
    <form action="{% url 'assessment:user_login' %}" method="post">
      {% csrf_token %}
      <div class="form-group">
        <label for="exampleInputEmail1">UserName</label>
        <input type="text" class="form-control" name="username" placeholder="Enter Username">
      </div>
      <div class="form-group">
        <label for="exampleInputPassword1">Password</label>
        <input type="password" class="form-control" name="password" placeholder="Enter Password">
      </div>
      <button type="submit" class="btn btn-primary">Submit</button>
    </form>
  </div>
</div>
{% endblock %}

OmniLearn/LMS/assessment/templates/assessment/userassements_list.html
{% extends "assessment/base.html" %}
{% block body_block %}

<div class="mt-5"></div>
<form id="resultForm" class="d-none">
  {{form.as_p}}
</form>
{% if myAssments|length > 0 %}
<h3 class="text-center">Assessment results and interpretation</h3>
<div class="mt-5"></div>
<div class="row">
  <div class="col-sm-12 col-xs-12 col-lg-3 col-xl-3">
    <aside class="sidebar">
      <nav>
        <ul>
            {% for assessment in myAssments %}
              {% if forloop.counter == 1 %}
                <li><a class="findResult" id={{assessment.pk}}><span id="firstClick"><b>{{assessment.created_date|date:"d M, Y, h:i A T"}}</b></span></a></li>
              {% else %}
                <li><a class="findResult" id={{assessment.pk}}><b>{{assessment.created_date|date:"d M, Y, h:i A T"}}</b></a></li>
              {% endif %}
            {% endfor %}
        </ul>
      </nav>
    </aside>
  </div>
  <div class="col-sm-12 col-xs-12 col-lg-9 col-xl-9 bordered">
    <div id="overlay">
      <div class="loader"></div>
    </div>
    <h3 id="assessmentTime"></h3>
    <div class="form-result">
      <p><b>Based on your responses, Your scores on various parameters of Wellbeing are as follows:</b></p>
      <table id="result-table1" class="table table-striped table-bordered">
        <tbody>
        </tbody>
      </table>
      <div id="betText">

      </div>
      <table id="result-table2" class="table table-striped table-bordered">
        <tbody>
        </tbody>
      </table>
      <p>&nbsp;</p>
      <p id="levelOfStressSentance1"></p>
      <p id="levelOfStressSentance2"></p>
      <p><b>Based on your responses & preference, you may begin your navigation journey from:</b></p>
      <div class="insprio">

      </div>
      <p><b>Disclaimer: Test results on the self-assessment scale do not reflect any particular diagnosis or course of treatment.
        They are meant as a tool to help assess your current level of Stress and Wellbeing. Should you have any further concerns about your current well-being, you may contact a certified medical physician.</b></p>
    </div>
  </div>
</div>
<div class="row mb-5 mt-3">
  <div class="col-sm-12 text-center">
    <p>If you learn to create the right climate in your body, mind, and emotion, your health, wellbeing, and joy - everything will be taken care of.
      <span> <b>- Sadhguru</b> </span>
    </p>
  </div>
</div>
<div class="d-none">
  <form id="resultForm">
    <input type="number" id="id_A1">
    <input type="number" id="id_A2">
    <input type="number" id="id_A3">
    <input type="number" id="id_M1">
    <input type="number" id="id_M2">
    <input type="number" id="id_M3">
    <input type="number" id="id_N1">
    <input type="number" id="id_N2">
    <input type="number" id="id_N3">
    <input type="number" id="id_E1">
    <input type="number" id="id_E2">
    <input type="number" id="id_E3">
    <input type="number" id="id_H1">
    <input type="number" id="id_H2">
    <input type="number" id="id_H3">
    <input type="number" id="id_R1">
    <input type="number" id="id_R2">
    <input type="number" id="id_R3">
    <input type="number" id="id_P1">
    <input type="number" id="id_P2">
    <input type="number" id="id_P3">
    <input type="number" id="id_Lon">
    <input type="number" id="id_hap">

    <input type="text" id="id_Q1">
    <input type="text" id="id_Q2">
    <input type="text" id="id_Q3">
    <input type="text" id="id_Q4">
    <input type="text" id="id_Q5">
    <input type="text" id="id_Q6">
    <input type="text" id="id_Q7">
    <input type="text" id="id_Q8">
    <input type="text" id="id_Q9">
    <input type="text" id="id_Q10">
    <input type="text" id="id_Q11">
    <input type="text" id="id_Q12">

    <input type="checkbox" id="CHQ1">
    <input type="checkbox" id="CHQ2">
    <input type="checkbox" id="CHQ3">
    <input type="checkbox" id="CHQ4">
    <input type="checkbox" id="CHQ5">
    <input type="checkbox" id="CHQ6">
    <input type="checkbox" id="CHQ7">
    <input type="checkbox" id="CHQ8">
  </form>
</div>
{% else %}
  <div class="no-record-message">
    <h3>No, Assessment Found</h3>
    <p>Please Submit Atleast One assessment and come back. <a href="{% url 'assessment:home' %}">Click Here</a> for submit</p>
  </div>
{% endif %}
<script type="text/javascript">
  $(document).ready(function(){
    $("#firstClick").closest(".findResult").click();
  });
  $(".findResult").on("click",function(){
    $("#overlay").show();
    var timeText = $(this).text();
    $(".findResult").removeClass("activeLi");
    $(this).addClass("activeLi");
    $.ajax({
      url: '/ajax/userResult/',
      data: {
        'pk':$(this).attr("id")
      },
      dataType:'json',
      success: function(data){
        //$("#assessmentTime").html(timeText);
        $("#id_A1").val(data.A1);
        $("#id_A2").val(data.A2);
        $("#id_A3").val(data.A3);
        $("#id_M1").val(data.M1);
        $("#id_M2").val(data.M2);
        $("#id_M3").val(data.M3);
        $("#id_P1").val(data.P1);
        $("#id_P2").val(data.P2);
        $("#id_P3").val(data.P3);
        $("#id_R1").val(data.R1);
        $("#id_R2").val(data.R2);
        $("#id_R3").val(data.R3);
        $("#id_H1").val(data.H1);
        $("#id_H2").val(data.H2);
        $("#id_H3").val(data.H3);
        $("#id_N1").val(data.N1);
        $("#id_N2").val(data.N2);
        $("#id_N3").val(data.N3);
        $("#id_E1").val(data.E1);
        $("#id_E2").val(data.E2);
        $("#id_E3").val(data.E3);
        $("#id_hap").val(data.hap);
        $("#id_Lon").val(data.Lon);

        $("#id_Q1").val(data.Q1);
        $("#id_Q2").val(data.Q2);
        $("#id_Q3").val(data.Q3);
        $("#id_Q4").val(data.Q4);
        $("#id_Q5").val(data.Q5);
        $("#id_Q6").val(data.Q6);
        $("#id_Q7").val(data.Q7);
        $("#id_Q8").val(data.Q8);
        $("#id_Q9").val(data.Q9);
        $("#id_Q10").val(data.Q10);
        $("#id_Q11").val(data.Q11);
        $("#id_Q12").val(data.Q12);
        $("#CHQ1").prop('checked',data.CQ1);
        $("#CHQ2").prop('checked',data.CQ2);
        $("#CHQ3").prop('checked',data.CQ3);
        $("#CHQ4").prop('checked',data.CQ4);
        $("#CHQ5").prop('checked',data.CQ5);
        $("#CHQ6").prop('checked',data.CQ6);
        $("#CHQ7").prop('checked',data.CQ7);
        $("#CHQ8").prop('checked',data.CQ8);
        doMentalWellbeingAssessment();
        setTimeout(function(){$("#overlay").hide();},500);
      }
    });
  });
</script>
{% endblock %}